### ISSUE TITLE
Question: Is there a way disable on a singular image?

### ISSUE THREAD

**Issue by 3200pro** [robinmetral/gatsby-plugin-pinterest#60]
Great work! Quick question:

Is there a way to disable the pin on a singular image? The only image I'd l like to disable is the logo within the header throughout the site.

Thanks!

**Comment by robinmetral** [comment]
Hey @3200pro, happy that this is helping! I haven't run into this use case before so I'm not sure—but since this essentially just injects the Pinterest script into your site, maybe there's documentation about this in the Pinterest Developer docs?

Unfortunately I don't have time to look into this right now, but I'll leave the issue open in case anyone else found a solution and wants to pitch in. And if you find a solution yourself, it would be awesome if you could send it in this issue thread so I can add it to the README! 🙂

**Comment by moonmeister** [comment]
Thanks for your interest in this project. This plugin is moving into the [Gatsby User Collective](https://github.com/gatsby-uc/plugins) and this repo will be archived. Please open an [issue](https://github.com/gatsby-uc/plugins/issues/new/choose) in that repository, submit a PR if you'd like to see this implemented, or join us on [Discord](discord.gg/gwnqfzetjv) if you have questions!
